#!/usr/bin/env bash
set -euo pipefail

# ==============================================================================
# run_sweeps.sh
# ==============================================================================
#
# Run one-variable-at-a-time parameter sweeps for the high-priority benchmark
# scenes:
#
#   1. ramp_cup       -> scripts/generate_ramp_cup_sweep.py
#   2. robotic_pour   -> scripts/generate_robotic_pour_sweep.py
#   3. pendulum       -> scripts/generate_pendulum_sweep.py
#
# Each sweep varies exactly one physical/action parameter while holding the
# rest of the scene fixed. This produces simulation folders containing metadata,
# resolved_config.json, result.npz / trajectory.npz, and videos by default. To disable video generation, use the --no-videos flag.
#
# ------------------------------------------------------------------------------
# Basic usage
# ------------------------------------------------------------------------------
#
# Make executable:
#
#   chmod +x scripts/run_sweeps.sh
#
# Run all high-priority sweeps without videos:
#
#   ./scripts/run_sweeps.sh --no-videos
#
# Run a small smoke test:
#   
#   ./scripts/run_sweeps.sh --quick
#
# Run a small smoke test with videos:
#
#   ./scripts/run_sweeps.sh --quick
#
# ------------------------------------------------------------------------------
# Selecting which simulations to run
# ------------------------------------------------------------------------------
#
# Available simulation names:
#
#   ramp_cup
#   robotic_pour
#   pendulum
#
# Run only pendulum:
#
#   ./scripts/run_sweeps.sh \
#     --sims pendulum
#
# Run only ramp-cup and robotic-pour:
#
#   ./scripts/run_sweeps.sh \
#     --sims ramp_cup robotic_pour
#
# ------------------------------------------------------------------------------
# Selecting seeds
# ------------------------------------------------------------------------------
#
# By default, full mode uses seeds:
#
#   0 1 2
#
# To specify your own seeds:
#
#   ./scripts/run_sweeps.sh \
#     --seeds 0 1 2 3 4
#
# Run only pendulum with five seeds:
#
#   ./scripts/run_sweeps.sh \
#     --sims pendulum \
#     --seeds 0 1 2 3 4
#
# ------------------------------------------------------------------------------
# Selecting parameters within each simulation
# ------------------------------------------------------------------------------
#
# By default, the script runs all high-priority parameters for each selected
# simulation.
#
# High-priority ramp_cup parameters:
#
#   ball_density
#   cup_density
#   ramp_angle_deg
#   fill_fraction
#   water_viscosity
#
# High-priority robotic_pour parameters:
#
#   water_viscosity
#   water_fill_fraction
#   pour_hold_seconds
#   pour_pose_fraction
#   water_density
#
# High-priority pendulum parameters:
#
#   length
#   gravity
#   damping
#   mass
#   theta0_deg
#
# To run only selected parameters, use:
#
#   --params sim_name:param1,param2
#
# Example: only viscosity sweeps for ramp-cup and robotic-pour:
#
#   ./scripts/run_sweeps.sh \
#     --sims ramp_cup robotic_pour \
#     --params ramp_cup:water_viscosity robotic_pour:water_viscosity \
#     --seeds 0 
# Example: one quick no-video smoke test for one parameter in each sim:
#
#   ./scripts/run_sweeps.sh \
#     --quick \
#     --no-videos \
#     --sims ramp_cup robotic_pour pendulum \
#     --params ramp_cup:ball_density robotic_pour:water_viscosity pendulum:length \
#     --seeds 0
#
# ------------------------------------------------------------------------------
# Output layout
# ------------------------------------------------------------------------------
#
# The script writes outputs under:
#
#   datasets/
#     ramp_cup_sweep/
#     robotic_pour_sweep/
#     pendulum_sweep/
#
# Each sweep folder should contain:
#
#   manifest.jsonl
#   manifest.csv
#   <sweep_param>/<scene_id>/
#     metadata.json
#     resolved_config.json
#     result.npz or trajectory.npz
#     video.mp4 or pendulum.mp4      # generated by default; use --no-videos to disable
#
# After generating sweeps with videos, build the VLM prompt dataset with:
#
#   uv run scripts/build_vlm_prompt_dataset.py \
#     --datasets-root outputs/datasets \
#     --output-root datasets/vlm_prompt_dataset
#
# ------------------------------------------------------------------------------
# Notes
# ------------------------------------------------------------------------------
#
# - Use --quick first to validate the pipeline.
# - Use full mode without videos to validate metadata and numerical outputs.
# - ramp_cup, robotic_pour, and pendulum are currently run with uv. 
#
# ==============================================================================

RUN_VIDEOS=1
QUICK=0

# Defaults
SIMS=("ramp_cup" "robotic_pour" "pendulum")
# SEEDS=(0 1 2)
SEEDS=(0)

# Optional per-simulation parameter overrides.
# Empty means: run high-priority params for that simulation.
RAMP_PARAMS_OVERRIDE=""
POUR_PARAMS_OVERRIDE=""
PEND_PARAMS_OVERRIDE=""

while [[ $# -gt 0 ]]; do
  case "$1" in
    --no-videos)
      RUN_VIDEOS=1
      shift
      ;;
    --quick)
      QUICK=1
      shift
      ;;
    --sims)
      shift
      SIMS=()
      while [[ $# -gt 0 && "$1" != --* ]]; do
        SIMS+=("$1")
        shift
      done
      ;;
    --seeds)
      shift
      SEEDS=()
      while [[ $# -gt 0 && "$1" != --* ]]; do
        SEEDS+=("$1")
        shift
      done
      ;;
    --params)
      shift
      while [[ $# -gt 0 && "$1" != --* ]]; do
        item="$1"
        sim="${item%%:*}"
        params="${item#*:}"

        case "$sim" in
          ramp_cup)
            RAMP_PARAMS_OVERRIDE="$params"
            ;;
          robotic_pour)
            POUR_PARAMS_OVERRIDE="$params"
            ;;
          pendulum)
            PEND_PARAMS_OVERRIDE="$params"
            ;;
          *)
            echo "Unknown sim in --params: $sim"
            exit 1
            ;;
        esac
        shift
      done
      ;;
    *)
      echo "Unknown argument: $1"
      echo "Valid options:"
      echo "  --no-videos"
      echo "  --quick"
      echo "  --sims ramp_cup robotic_pour pendulum"
      echo "  --seeds 0 1 2"
      echo "  --params ramp_cup:ball_density,fill_fraction robotic_pour:water_viscosity pendulum:length,damping"
      exit 1
      ;;
  esac
done

contains_sim () {
  local target="$1"
  for sim in "${SIMS[@]}"; do
    if [[ "$sim" == "$target" ]]; then
      return 0
    fi
  done
  return 1
}

comma_to_array () {
  local input="$1"
  local -n out_array="$2"
  IFS=',' read -r -a out_array <<< "$input"
}

DATASETS_ROOT="datasets"
RAMP_OUT="${DATASETS_ROOT}/ramp_cup_sweep"
POUR_OUT="${DATASETS_ROOT}/robotic_pour_sweep"
PEND_OUT="${DATASETS_ROOT}/pendulum_sweep"

# make folders only for the sims to run
if contains_sim "ramp_cup"; then
  mkdir -p "$RAMP_OUT"
fi
if contains_sim "robotic_pour"; then
  mkdir -p "$POUR_OUT"
fi
if contains_sim "pendulum"; then
  mkdir -p "$PEND_OUT"
fi

if [[ "$QUICK" -eq 1 ]]; then
  echo "[mode] QUICK validation sweeps"

  RAMP_NUM_FRAMES=120
  POUR_NUM_FRAMES=120
  PEND_NUM_STEPS=360

  RAMP_VALUES_BALL_DENSITY="650,2700,7850"
  RAMP_VALUES_CUP_DENSITY="450,1000,2500"
  RAMP_VALUES_RAMP_ANGLE="10,20,30"
  RAMP_VALUES_FILL="0.25,0.55,0.85"
  RAMP_VALUES_VISCOSITY="0.0003,0.003,0.03"

  POUR_VALUES_VISCOSITY="0.0003,0.003,0.03"
  POUR_VALUES_FILL="0.40,0.80,0.97"
  POUR_VALUES_HOLD="0.0,1.0,4.0"
  POUR_VALUES_POSE="0.65,0.80,0.92"
  POUR_VALUES_DENSITY="850,1000,1450"

  PEND_VALUES_LENGTH="0.5,1.0,2.0"
  PEND_VALUES_GRAVITY="3.71,9.81,24.79"
  PEND_VALUES_DAMPING="0.0,0.02,0.10"
  PEND_VALUES_MASS="0.1,1.0,5.0"
  PEND_VALUES_THETA="5,30,90"

else
  echo "[mode] FULL high-priority sweeps"

  RAMP_NUM_FRAMES=240
  POUR_NUM_FRAMES=480
  PEND_NUM_STEPS=1200

  RAMP_VALUES_BALL_DENSITY="300,650,1000,2700,4500,7850,12000"
  RAMP_VALUES_CUP_DENSITY="250,450,650,1000,1450,2500,5000"
  RAMP_VALUES_RAMP_ANGLE="5,10,15,20,25,30,35"
  RAMP_VALUES_FILL="0.10,0.25,0.40,0.55,0.70,0.85,0.95"
  RAMP_VALUES_VISCOSITY="0.0001,0.0003,0.001,0.003,0.01,0.03,0.1"

  POUR_VALUES_VISCOSITY="0.0001,0.0003,0.001,0.003,0.006,0.01,0.03"
  POUR_VALUES_FILL="0.25,0.40,0.55,0.70,0.80,0.90,0.97"
  POUR_VALUES_HOLD="0.0,0.25,0.5,1.0,1.5,2.5,4.0"
  POUR_VALUES_POSE="0.55,0.65,0.72,0.80,0.86,0.92,1.00"
  POUR_VALUES_DENSITY="700,850,1000,1150,1300,1450,1600"

  PEND_VALUES_LENGTH="0.35,0.50,0.75,1.00,1.25,1.50,2.00"
  PEND_VALUES_GRAVITY="1.62,3.71,5.0,9.81,12.0,15.0,24.79"
  PEND_VALUES_DAMPING="0.0,0.0025,0.005,0.01,0.02,0.05,0.10"
  PEND_VALUES_MASS="0.05,0.10,0.25,0.50,1.00,2.00,5.00"
  PEND_VALUES_THETA="2,5,10,20,35,60,90"
fi

if [[ "$RUN_VIDEOS" -eq 1 ]]; then
  echo "[mode] Rendering videos"
  RAMP_VIDEO_FLAG=()
  POUR_VIDEO_FLAG=()
  PEND_VIDEO_FLAG=(--render-video)
else
  echo "[mode] No videos"
  RAMP_VIDEO_FLAG=(--no-video)
  POUR_VIDEO_FLAG=(--no-video)
  PEND_VIDEO_FLAG=()
fi

echo "[config] simulations: ${SIMS[*]}"
echo "[config] seeds: ${SEEDS[*]}"

# -----------------------------
# Ramp-cup-water
# -----------------------------
if contains_sim "ramp_cup"; then
  echo ""
  echo "============================================================"
  echo "Ramp-cup-water sweeps"
  echo "============================================================"

  RAMP_PARAMS=(
    "ball_density:${RAMP_VALUES_BALL_DENSITY}"
    "cup_density:${RAMP_VALUES_CUP_DENSITY}"
    "ramp_angle_deg:${RAMP_VALUES_RAMP_ANGLE}"
    "fill_fraction:${RAMP_VALUES_FILL}"
    "water_viscosity:${RAMP_VALUES_VISCOSITY}"
  )

  if [[ -n "$RAMP_PARAMS_OVERRIDE" ]]; then
    comma_to_array "$RAMP_PARAMS_OVERRIDE" RAMP_PARAM_NAMES
  else
    RAMP_PARAM_NAMES=("ball_density" "cup_density" "ramp_angle_deg" "fill_fraction" "water_viscosity")
  fi

  for item in "${RAMP_PARAMS[@]}"; do
    param="${item%%:*}"
    values="${item#*:}"

    should_run=0
    for selected in "${RAMP_PARAM_NAMES[@]}"; do
      if [[ "$selected" == "$param" ]]; then
        should_run=1
      fi
    done
    [[ "$should_run" -eq 1 ]] || continue

    echo ""
    echo "[ramp-cup] sweeping ${param}"
    uv run scripts/generate_ramp_cup_sweep.py \
      --sweep-param "$param" \
      --values "$values" \
      --seeds "${SEEDS[@]}" \
      --num-frames "$RAMP_NUM_FRAMES" \
      --output-root "$RAMP_OUT" \
      "${RAMP_VIDEO_FLAG[@]}"
  done
fi

# -----------------------------
# Robotic-pour
# -----------------------------
if contains_sim "robotic_pour"; then
  echo ""
  echo "============================================================"
  echo "Robotic-pour sweeps"
  echo "============================================================"

  POUR_PARAMS=(
    "water_viscosity:${POUR_VALUES_VISCOSITY}"
    "water_fill_fraction:${POUR_VALUES_FILL}"
    "pour_hold_seconds:${POUR_VALUES_HOLD}"
    "pour_pose_fraction:${POUR_VALUES_POSE}"
    "water_density:${POUR_VALUES_DENSITY}"
  )

  if [[ -n "$POUR_PARAMS_OVERRIDE" ]]; then
    comma_to_array "$POUR_PARAMS_OVERRIDE" POUR_PARAM_NAMES
  else
    POUR_PARAM_NAMES=("water_viscosity" "water_fill_fraction" "pour_hold_seconds" "pour_pose_fraction" "water_density")
  fi

  for item in "${POUR_PARAMS[@]}"; do
    param="${item%%:*}"
    values="${item#*:}"

    should_run=0
    for selected in "${POUR_PARAM_NAMES[@]}"; do
      if [[ "$selected" == "$param" ]]; then
        should_run=1
      fi
    done
    [[ "$should_run" -eq 1 ]] || continue

    echo ""
    echo "[robotic-pour] sweeping ${param}"
    uv run scripts/generate_robotic_pour_sweep.py \
      --sweep-param "$param" \
      --values "$values" \
      --seeds "${SEEDS[@]}" \
      --num-frames "$POUR_NUM_FRAMES" \
      --output-root "$POUR_OUT" \
      "${POUR_VIDEO_FLAG[@]}"
  done
fi

# -----------------------------
# Pendulum
# -----------------------------
if contains_sim "pendulum"; then
  echo ""
  echo "============================================================"
  echo "Pendulum sweeps"
  echo "============================================================"

  PEND_PARAMS=(
    "length:${PEND_VALUES_LENGTH}"
    "gravity:${PEND_VALUES_GRAVITY}"
    "damping:${PEND_VALUES_DAMPING}"
    "mass:${PEND_VALUES_MASS}"
    "theta0_deg:${PEND_VALUES_THETA}"
  )

  if [[ -n "$PEND_PARAMS_OVERRIDE" ]]; then
    comma_to_array "$PEND_PARAMS_OVERRIDE" PEND_PARAM_NAMES
  else
    PEND_PARAM_NAMES=("length" "gravity" "damping" "mass" "theta0_deg")
  fi

  for item in "${PEND_PARAMS[@]}"; do
    param="${item%%:*}"
    values="${item#*:}"

    should_run=0
    for selected in "${PEND_PARAM_NAMES[@]}"; do
      if [[ "$selected" == "$param" ]]; then
        should_run=1
      fi
    done
    [[ "$should_run" -eq 1 ]] || continue

    echo ""
    echo "[pendulum] sweeping ${param}"
    uv run python scripts/generate_pendulum_sweep.py \
      --sweep-param "$param" \
      --values "$values" \
      --seeds "${SEEDS[@]}" \
      --num-steps "$PEND_NUM_STEPS" \
      --output-root "$PEND_OUT" \
      "${PEND_VIDEO_FLAG[@]}"
  done
fi

echo ""
echo "============================================================"
echo "Done"
echo "============================================================"

echo "Datasets written under:"
# print folders for the sims that were run
if [[ -n "$RAMP_OUT" ]]; then
  RAMP_OUT=$(realpath "$RAMP_OUT")
fi
if [[ -n "$POUR_OUT" ]]; then
  POUR_OUT=$(realpath "$POUR_OUT")
fi
if [[ -n "$PEND_OUT" ]]; then
  PEND_OUT=$(realpath "$PEND_OUT")
fi
